### ISSUE TITLE
Could not load file or assembly 'System.ValueTuple'

### ISSUE THREAD

**Issue by kaspars-ozols** [marisks/FeaturesViewEngine#2]
Package NuSpec does not define dependency on `Sytem.ValueTuple` package. When deployed to server with older .NET version, this causes problems.

Either need to add dependency or change code not to use `ValueTuple` type.

**Comment by marisks** [comment]
Fixed in https://github.com/marisks/FeaturesViewEngine/commit/4c38f81bdc0c94079be76da4246987d55b1f21c9
